---
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: flask-app-db
spec:
  selector:
    matchLabels:
      type: db
      service: flask-app
  template:
    metadata:
      labels:
        type: db
        service: flask-app
        vendor: Redis
    spec:
      containers:
        - name: db
          image: redis:alpine
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-db
spec:
  ports:
    - port: 6379
  selector:
    type: db
    service: flask-app

---
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: flask-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      type: api
      service: flask-app
  template:
    metadata:
      labels:
        type: api
        service: flask-app
        language: python
    spec:
      containers:
        - name: api
          image: xomodo/flask-app:latest
      env:
        - name: REDIS_ENDPOINT
          value: flask-app-db

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-api
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    type: api
    service: flask-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  backend:
    serviceName: flask-app-api
    servicePort: 8080
